name: Check pull request

on:
  push:
    branches: ["*"]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.5"

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('frontend/bun.lock', 'frontend/package.json') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Install deps
        run: cd frontend && bun install

      - name: Run typecheck
        run: cd frontend && bun run tsc -p tsconfig.json

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.5"

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('frontend/bun.lock', 'frontend/package.json') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Install deps
        run: cd frontend && bun install

      - name: Run ESLint
        run: cd frontend && bun run lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.5"

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('frontend/bun.lock', 'frontend/package.json') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Install deps
        run: cd frontend && bun install

      - name: Run unit tests
        run: cd frontend && bun run test

  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rprtr258/apiary/ci:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Install frontend deps
        run: cd frontend && bun install

      - name: Install Go deps
        run: go mod tidy

      - name: Run E2E tests
        env:
          CI: "1"
        run: cd frontend && bun run test:e2e
